### ISSUE TITLE
Accessing options through task argument not "this" context

### ISSUE THREAD

**Issue by pawelgalazka** [pawelgalazka/tasksfile#77]
### Context
Currently to get access to cli dash options like:

```
$ npx run test --abc
```

we need to use `options` helper with giving `this` context to it:

```js
const { options } = require('runjs')

function test () {
  console.log('OPTIONS', options(this))
}
```

### Issues

1. This is in some cases problematic especially if we want to call task from other task but provide options to it:

```js
test.call({ options: { abc: true } })
```

which not really clear, obvious and convenient.

2. Fat arrow functions can't access `this`, so you can't handle options in those.

### Proposition

Let's pass `options` always as a first argument to task function, so we can access it like this:

```js
function test (options) {
  console.log('OPTIONS', options)
}
```

### Consideration

every task would need to accept and have declared `options` as first argument. May sound inconvenient, but handling options will be cleaner to grasp.

**Comment by ivan-kleshnin** [comment]
Plus this follows the API of your `microcli` dependency.

**Comment by markstos** [comment]
I already have some shared functions which accept custom arguments so they can be called different ways internally. I guess internal-only functions are safe from the change, because only the public functions would receive the argument.

However, this would be a compatibility problem for functions which are public and also *shared* using a custom argument passed. 

I think binding options to `this.options` in the task functions is OK, but also understand if you want to switch to this new API.

**Comment by pawelgalazka** [comment]
It's done already
