### ISSUE TITLE
Expose all options of underlying child_process call to run function

### ISSUE THREAD

**Issue by oliverhulett** [pawelgalazka/tasksfile#83]
Currently the `run()` function takes an `options` argument, to which it sanitises and adds some defaults, then passes those options to either `child_process.execSync()` or `child_process.spawn()`.

The method by which `options` is sanitised and the defaults added means the user cannot access all of the options exposed by the underlying `child_process` function that is called (my specific use case is to override the shell from `/bin/sh` to `/bin/bash`)

This seems unnecessarily restrictive, can we just strip the `runjs` options, add any `runjs` defaults (where they differ from the `child_process` defaults and have not been set by the user) and then pass the user's `options` argument directly to the underlying `child_process` call?

**Comment by markstos** [comment]
I would also like the 'shell' option to be exposed and further propose that the default be changed from from `sh` to `bash`. I think this follows the "principle of least surprise", as developers are more likely to be expecting bash semantics.

Further, I propose that `shopt -s globstar` be turned on by default for this shell. 

People coming from Gulp and other build systems often use patterns like this to match files, using the double star syntax, aka the "globstar":

      **/*.svg

This has been supported by default since 2010, but is not enabled by default.

**Comment by markstos** [comment]
I'm going to work on a pull request for this now.

**Comment by ljani** [comment]
This is a little related to the same issue: I'd be interested in having direct access to [`asyncProcess.stdout`](https://github.com/pawelgalazka/tasksfile/blob/b7992457db8c4adead4a68440d5887262d94ddbc/src/index.ts#L74), so I could do some muxing for parallel async processes. Any thoughts?

Btw, I'm using `runjs` on Windows and I do not have `bash` in my `PATH`. I'd be surprised if I needed to configure something to get `runjs` to run.

**Comment by pawelgalazka** [comment]
@ljani `sh` command is designed to be very simple and straightforward, so it returns a promise and it has the same options between async and sync option, that are the base assumptions of it. If you need more, nothing stops you to use original `child_process` module within `tasksfile` command

**Comment by pawelgalazka** [comment]
One planned thing is to add `shell` option but apart from that passing all options is not planned
